name: dask_jobqueue_workshop
channels:
  - conda-forge
dependencies:
  - python=3
  - bokeh
  - dask
  - distributed
  - git
  - git-lfs
  - hdf5
  - ipykernel
  - matplotlib
  - netCDF4
  - numba
  - numpy
  - pandas
  - pip
  - seaborn
  - tornado
  - xarray
  - zarr
  - pip:
    - git+https://github.com/dask/dask-jobqueue@9c3371d17d943dd44103225c814b8ee042513a93
